name = "expense-tracker"
compatibility_date = "2024-11-06"
pages_build_output_dir = "dist/expense-tracker/browser"

# Routes configuration
#routes = [
#  { pattern = "/api/*", zone_name = "pages.dev" },
#  { pattern = "/*", zone_name = "pages.dev" }
#]

[[kv_namespaces]]
binding = "EXPENSES_KV"
id = "8ee394822c6748a2b698b0f1c47e7167"
preview_id = "8d2f65ed84ce4c0a9dd10e0091d9b806"

[vars]
NODE_ENV = "development"
NODE_VERSION = "20.x"

[env.production.vars]
NODE_ENV = "production"
NODE_VERSION = "20.x"

[[env.production.kv_namespaces]]
binding = "EXPENSES_KV"
id = "8ee394822c6748a2b698b0f1c47e7167"
preview_id = "8d2f65ed84ce4c0a9dd10e0091d9b806"



